---
- name: Update and Upgrade Ubuntu/Debian based systems
  hosts: all
  become: true

  tasks:
  - name: Update package index
    apt:
      update_cache: yes

  - name: Upgrade all packages
    apt:
      upgrade: full

  - name: Reboot the system
    reboot:
      reboot_timeout: 600
      when: True
